FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src
COPY ./WebAPI/WebAPI.csproj ./WebAPI/WebAPI.csproj
COPY ./Application/Application.csproj ./Application/Application.csproj
COPY ./Infrastructure/Infrastructure.csproj ./Infrastructure/Infrastructure.csproj
COPY ./Domain/Domain.csproj ./Domain/Domain.csproj
RUN dotnet restore ./WebAPI/WebAPI.csproj
COPY . .
RUN dotnet publish ./WebAPI -c Release -o /release

FROM base as final
RUN apt-get update
RUN apt-get install -y curl
WORKDIR /app
COPY --from=build /release .
EXPOSE 80
ENTRYPOINT ["dotnet", "WebAPI.dll"]